#!/usr/bin/env python
# -*- coding: utf-8 -*-
# bot.py
elfNamesFemale = [
                    "Aelene", "Aelinor", "Aemma", "Akash", "Alaesa", "Alaglossa", "Alais",
                    "Alauthshae", "Alavara", "Alea", "Alerathla", "Allannia", "Alloralla",
                    "Alys", "Amaryll" "Aquilaen", "Aredhel", "Arwen", "Axilia", "Ayaeqlarune",
                    "Azariah", "Baelen", "Beala", "Bhuraelea", "Blythswana", "Bonnalurie",
                    "Braerindra", "Caerthynna", "Calarel", "Cauladra", "Celebrían", "Chandrelle",
                    "Chasianna", "Chichlandra", "Chin’nesstre", "Chomylla", "Ciyradyl",
                    "Daealla", "Daena", "Daenestra", "Daenys", "Daeondra", "Doreah", "Elaria",
                    "Elenwe", "Ellania", "Elora", "Elwing", "Elyss", "Fhaertala", "Filaurel",
                    "Filauria", "Fildaerae", "Finduilas", "Fraeya", "Gaelira", "Gaerradh",
                    "Galadriel", "Gaylia", "Ghilanna", "Gilgalad", "Glorfindel", "Glynnii",
                    "Gweyr", "Gwynnestri", "Gylledha", "Haalija", "Hacathra", "Haela",
                    "Halaema", "Halaena", "Halama", "Halanaestra", "Hameada", "Holcene",
                    "Holone", "Hycis", "Iahalae", "Ialantha", "Idril", "Ikeshia", "Ilmadia",
                    "Ilyrana", "Ilythyrra", "Imdalac", "Imizael", "Irithiel", "Ithirae",
                    "Iziuel", "Jahandra", "Kaeda", "Kaylessa", "Keara", "Keerla", "Keishara",
                    "Kethryllia", "Keya", "Kyrrha", "Kythaela", "Laamtora", "Laeanna",
                    "Laena", "Laerdya", "Lazziar", "Leandra", "Leilatha", "Liluth", "Llamryl",
                    "Lorelei", "Lúthien", "Lyraesel", "Maaleshiira", "Maegelle", "Maelyrra",
                    "Maeralya", "Mariah", "Meara", "Mereena", "Merlara", "Miriel", "Morwen",
                    "Mylaela", "Myrynda", "Nuovis", "Nushala", "Nylaathria", "Ochyllyss",
                    "Oluevaera", "Phaerl", "Phantyni", "Phelorna", "Phuingara", "Phyrra",
                    "Quaela", "Quamara", "Raejiisa", "Raerauntha", "Rathiain", "Reinys",
                    "Renestrae", "Rubrae", "Ryllae", "Saelihn", "Saélihn", "Saeya", "Sasha",
                    "Shalana", "Shalantha", "Shalheira", "Shandalar", "Shanyrria", "Sharaera",
                    "Sheedra", "Shiera", "Shyael", "Shyllisyrr", "Sinnafain", "Soliania",
                    "Soora", "Sorsasta", "Susklahava", "Sylmae", "Symrustar", "Syndra", "Synnorha",
                    "Syrenese", "Syrune", "Syviis", "Taena", "Taenya", "Taeriel", "Takari",
                    "Talaedra", "Talanashta", "Talila", "Talilia", "Talindra", "Tamara",
                    "Tarasynora", "Teharissa", "Tiatha", "Tsarra", "Tyria", "Urmicca", "Vaella",
                    "Valindra", "Veara", "Vestele", "Viansola", "Violen", "Viserra", "Yaereene",
                    "Yalanilue", "Yathlanae", "Ynshael", "Yrlissa", "Yrneha", "Yrniela",
                    "Zeale", "Zhuirentel"
                 ]
elfNameMale = [
                "Aego", "Aelrindel", "Aerendyl", "Aeson", "Afamrail", "Agis", "Ailmar",
                "Aithlin", "Akkar", "Alabyran", "Aranel", "Arazorwyn", "Beleg", "Beluar",
                "Biafyndar", "Bialaer", "Braern", "Briareth", "Cameron", "Celeborn",
                "Celebrimbor", "Chathanglas", "Cheyrth", "Círdan", "Cluhurach", "Cluym",
                "Cohnal", "Conall", "Connak", "Cornaith", "Corym", "Curunir", "Cymbiir",
                "Cystenn", "Daeharice", "Daemeon", "Dakath", "Dalyor", "Darcassan", "Dior",
                "Earendil", "Edrahil", "Eladithas", "Elanjar", "Elaran", "Elashor",
                "Elbauthin", "Elbereth", "Eldaernth", "Eldar", "Eldrin", "Elénaril",
                "Elenshaer", "Elrond", "Eluchil", "Elwin", "Erlan", "Erlathan", "Eroan",
                "Erolith", "Eschallus", "Estelar", "Etchelion", "Ethlando", "Ettrian",
                "Evindal", "Eyrynnhv", "Eyrynnhv", "Faelar", "Faelyn", "Faeranduil",
                "Falael", "Fëanor", "Fenris", "Filvendor", "Fingolfin", "Finrod",
                "Folduin", "Gael", "Gaemon", "Gil-galad", "Glynkas", "Haemir", "Hagduin",
                "Haladavar", "Halafarin", "Haryk", "Hastos", "Hatharal", "Herbalar",
                "Horith", "Hubyr", "Iarmenor", "Iefyr", "Ievos", "Ilbryn", "Iliven",
                "Ilthuryn", "Inarie", "Inchel", "Inialos", "Injros", "Intevar", "Iolas",
                "assin", "Jhaan", "Jhaartael", "Jhaeros", "Kelkalyn", "Kevan", "Klaern",
                "Kolvar", "Kuornos", "Kuskyn", "Kymil", "Kyrenic", "Kyrtaar",
                "lrune", "Maiele", "Mithrandir", "Molonym", "Molostroi", "Montagor",
                "Morgan", "Morthil", "Myrddin", "Myriil", "Myrin", "Mythanthar", "Naertho",
                "Naeryndam", "Napraeleon", "Narbeth", "Nardual", "Nelaeryn", "Neldor",
                "Nerilamin", "Nesterin", "Nevarth", "Nhamashal", "Nieven", "Nindr",
                "Nym", "Onas", "Oribel", "Oritris", "Orndacil", "Ornthalas", "Orris",
                "Orym", "Oslarelar", "Otaehryn", "Othorion", "Paeral", "Paeris", "Phaendar",
                "Pharom", "Phraan", "Pirphal", "Pleufan", "Purtham", "Pyrder", "Quaeth",
                "Raegel", "Raunaeril", "Ravaphine", "Reysalor", "Rhistel", "Saelethil",
                "Saevel", "Seiveril", "Sharian", "Siirist", "Silvyr", "Sudryl", "Taenaran",
                "Taerntym", "Tamnaeuth", "Tannivh", "Tassarion", "Tehlmar", "Therona",
                "Thingol", "Thranduil", "Toross", "Travaran", "Triandal", "Turgon",
                "Usunaar", "Uthorim", "Vaalyun", "Vaegon", "Vaeril", "Venrie", "Virjeon",
                "Yhendorn", "Ylyndar", "Zabbas", "Zaltarish",
            ]
elfNameAndrogynous = ["Alva", "Aubrey", "Avery", "Cindertine", "Elowen", "Aelinor", "Akash",
                      "Alais", "Baelen", "Elwing", "Gaerradh", "Keya", "Nuovis", "Aithlin",
                      "Círdan", "Corym", "Dior", "Elaran", "Erolith", "Ievos", "Inarie", "Kelkalyn",
                      "Maiele", "Morgan", "Myrin", "Sharian", "Therona"
                      ]
elfLastNames = [
                "Adanell", "Aelasar", "Aelorothi", "Aendryr", "Aerasumé", "Aeravansel",
                "Aldaval", "Aloiene", "Alqualonde", "Amaratharr", "Amarthen", "Ammath",
                "Amrallatha", "Anuaer", "Ardorius", "Artordhron", "Augalvaryl", "Beinion",
                "Beor", "Braegen", "Briarbosk", "Brightcloak", "Brightsong", "Brightspear",
                "Brightstar", "Brightwing", "Castien", "Caundur", "Celelaeth", "Cererindur",
                "Chamaranthe", "Clatharla", "Corellon", "Cormyth", "Coudoarluth", "Craulnober",
                "Crystalis", "Cubrinmyr", "Darkbrood", "Darkcloak", "Darkwing", "Deryth",
                "Dor-lomin", "Dragonrider", "Eaglelord", "Ealoloth", "Ealoviel", "Earcorn",
                "Elaéyadar", "Elassidil", "Elerelwa", "Elian", "Elkenmage", "Ellarian",
                "Elond", "Erladden", "Erlshade", "Eroth", "Eruien", "Erunonidan", "Estelda",
                "Evanara", "Faefindas", "Faelen", "Faenion", "Faenor", "Faerondalan",
                "Felarathael", "Finwe", "Floralei", "Flyleaf", "Frostfang", "Gaelen",
                "Galaalta", "Goldenleaf", "Gourael", "Greencloak", "Gwaelon", "Hadirsyr",
                "Hador", "Haell", "Haerlgent", "Haleth", "Hasterien", "Hatanar", "Helion",
                "Hessarion", "Idhtulcdrach", "Ievos", "Iliathorr", "Ilnatar", "Immeril",
                "Impanton", "Imphenon", "Ipyllasc", "Irian", "Isiliraiellyn", "Kadhorduil",
                "Kithsidhion", "Kraok", "Laedireil", "Laelithar", "Lannarseer", "Laralytha",
                "Larbrinlal", "Larenthanil", "Larethian", "Lashrael", "Lassagaseer", "Lasslail",
                "Leaadion", "Liondale", "Lithelon", "Lithron", "Maedhros", "Maeglin", "Maeir",
                "Maertel", "Magor", "Maltathdar", "Moondown", "Moonflower", "Moonford",
                "Moonglade", "Moonshrine", "Moorfly", "Nenaias", "Nhachashaal", "Nhaéslal",
                "Nharimlur", "Nightstar", "Nightswatch", "Nightwing", "Noldorin", "Norodiir",
                "Northstar", "Oaktree", "Ongluth", "Orama", "Orbryn", "Quendi", "Redwing",
                "Rhothomir", "Rhuidhen", "Rhyllgallohyr", "Rivleam", "Rivvikyn", "Runemaster",
                "Sarsantyr", "Selakiir", "Selmer", "Shinestar", "Shiredove", "Silkstream",
                "Siltral", "Silverbow", "Silverhand", "Silveroak", "Silverspear", "Simserion",
                "Snowfell", "Snowreign", "Stillhawk", "Stilmyst", "Stormspear", "Straeth",
                "Strongbow", "Suldusk", "Sunfoal", "Sunshield", "Sunstar", "Sylleth",
                "Tassarion", "Tathdel", "Taurntyrith", "Telerie", "Tellynnan", "Teshurr",
                "Thalien", "Thoimion", "Thothiion", "Thundruil", "Tipantdon", "Turnvale",
                "Tyrell", "Vanamaeduil", "Vanvathar", "Vispasial", "Voronbund", "Vyshaan",
                "Waelvor", "Werloththar", "Whitethistle", "Windslore", "Windstar", "Windwalker",
                "Wingglide", "Wintermoon", "Wolfspeak", "Yrauos"
               ]
batMaleNames = [
                'Matrix', 'Fuzz', 'Tiberius', 'Impaler', 'Shrike', 'Vulkan', 'Butch', 'Guano',
                'Ripmaw', 'Vamp', 'Nightmare', 'Baxter', 'Azar', 'Lockjaw', 'Booboo', 'Darth',
                'Dimitri', 'Blues', 'Moon', 'Shrike', 'Midnight', 'Sonar', 'Flaps', 'Screech',
                'Draculon', 'Sabath', 'Angel', 'Vladimir', 'Grey', 'Spuds', 'Dexter', 'Mothra',
                'Cole', 'Dimitri', 'Archangel', 'Bruce', 'Drake', 'Comet', 'Spectre', 'Rascal',
                'Blade', 'Nyx', 'Basil', 'Char', 'Wingnut', 'Orion', 'Shadow', 'Brutus', 'Ash',
                'Lucifer'
               ]
batFemaleNames = [
                    'Angel', 'Trixy', 'Ruth', 'Rhyme', 'Rhyme', 'Echo', 'Mirage', 'Flutters',
                    'Bandetta', 'Giggles', 'Sona', 'Dawnstar', 'Nibbles', 'Harmony', 'Equina',
                    'Siren', 'Mittens', 'Sage', 'Cookie', 'Dawnstar', 'Moonlight', 'Shine', 'Haze',
                    'Lady', 'Scarlett', 'Illumina', 'Ivy', 'Morning', 'Abby', 'Sade', 'Aine',
                    'Shade', 'Velvet', 'Aura', 'Azurys', 'Dot', 'Equinox', 'Twilight', 'Iris',
                    'Cerulean', 'Star', 'Violet', 'Raine', 'Lucy', 'Nugget', 'Indigo', 'Skye',
                    'Skylar', 'Morticia'
                 ]
